name: micro-domains-mono-test
services:
  mariadb:
    image: mariadb:11.4.5
    environment:
      MARIADB_DATABASE: micro_domains
      MARIADB_USER: micro_domains
      MARIADB_PASSWORD: micro_domains
      MARIADB_ROOT_PASSWORD: micro_domains_root
    ports:
      - "5306:3306"
    volumes:
      - micro-domains-mono-test-mariadb-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pmicro_domains_root" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: valkey/valkey:9.0-alpine3.22
    ports:
      - "5379:6379"
    volumes:
      - micro-domains-mono-test-redis-data:/data
    healthcheck:
      test: [ "CMD", "valkey-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    command: valkey-server --appendonly yes

volumes:
  micro-domains-mono-test-mariadb-data:
    driver: local
  micro-domains-mono-test-redis-data:
    driver: local
